version: '2'
services:
    courrier-app:
        image: courrier
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://courrier-mysql:3306/courrier?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    courrier-mysql:
        extends:
            file: mysql.yml
            service: courrier-mysql
